---
- name: Ensure Aegir's dependencies are installed.
  apt:
    name: "{{ item }}"
    state: installed
  when: (aegir_manage_dependencies == true) and (ansible_os_family == 'Debian')
  with_items: aegir_dependencies

- name: Install additional packages.
  apt:
    name: "{{ item }}"
    state: installed
  when: (aegir_install_additional_packages == true) and (ansible_os_family == 'Debian')
  with_items: aegir_additional_packages

# Ref.: http://community.aegirproject.org/installing/manual#Create_the_Aegir_user
- name: Create 'aegir' group
  group:
    name: "{{ aegir_user }}"
    system: yes
- name: Create 'aegir' user
  user:
    name: "{{ aegir_user }}"
    system: yes
    home: "{{ aegir_root }}"
    group: "{{ aegir_user }}"
    groups: "{{ aegir_web_group }}"
    append: yes

# Ref.: http://community.aegirproject.org/installing/manual#Install_provision
- name: Create 'aegir' user home.
  file:
    path: /var/aegir/
    state: directory
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"
- name: Create ~/.drush/ for 'aegir' user.
  file:
    path: /var/aegir/.drush
    state: directory
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"
- name: Clone Provision
  git:
    repo: "{{ aegir_provision_repo }}"
    dest: "{{ aegir_root }}/.drush/provision"
    depth: 1 # speeds things up
    version: "{{ aegir_provision_version }}"
    update: "{{ aegir_provision_update }}"
  sudo: yes
  sudo_user: "{{ aegir_user }}"
- name: Clear Drush cache for Provision extension
  command: drush @none cc drush
  args:
    creates: "{{ aegir_root }}/.drush/cache/"
  sudo: yes
  sudo_user: "{{ aegir_user }}"

# Ref.: http://community.aegirproject.org/installing/manual#Apache_configuration
- include: setup-apache.yml
  when: aegir_http_service_type == 'apache'

# Ref.: http://community.aegirproject.org/installing/manual#Sudo_configuration
- name: Configure sudo for aegir user
  copy:
    dest: "/etc/sudoers.d/{{ aegir_user }}"
    content: "{{ aegir_user }} ALL=NOPASSWD: /usr/sbin/apache2ctl\n{{ aegir_user }} ALL=NOPASSWD: /etc/init.d/nginx\n\n"
    mode: 0440

- name: Write Hostmaster makefile
  copy:
    dest: "{{ aegir_root }}/aegir.make"
    content: "{{ aegir_makefile_contents }}"
    owner: "{{ aegir_user }}"
    group: "{{ aegir_user }}"

- name: Build Hostmaster platform
  command: "drush make {{ aegir_root }}/aegir.make {{ aegir_root }}/hostmaster-{{ aegir_platform_version }} --working-copy --no-gitinfofile"
  args:
    creates: "{{ aegir_root }}/hostmaster-{{ aegir_platform_version }}/"
  sudo: yes
  sudo_user: "{{ aegir_user }}"

# Ref.: # http://community.aegirproject.org/installing/manual#Running_hostmaster-install
- name: Install Aegir front-end
  command: "drush @none --yes hostmaster-install --debug --working-copy --aegir_db_host={{ aegir_db_host }} --aegir_db_user={{ mysql_root_username }} --aegir_db_pass={{ mysql_root_password }} --aegir_version={{ aegir_platform_version }} {{ aegir_frontend_url }} --strict=0 --root={{ aegir_root }}/hostmaster-{{ aegir_platform_version }}/"
  args:
    creates: "{{ aegir_root }}/hostmaster-{{ aegir_platform_version }}/sites/{{ aegir_frontend_url }}/"
  sudo: yes
  sudo_user: "{{ aegir_user }}"

- include: generate-keypair.yml
  when: aegir_generate_keypair

- name: Ensure Hosting is recognized as enabled
  shell: drush @hostmaster cc drush
  sudo: yes
  sudo_user: "{{ aegir_user }}"
  changed_when: False
